# Uncomment the next line to define a global platform for your project
platform :ios, "14.3"

target 'Challo' do
  inhibit_all_warnings!
  use_frameworks!

  # Pods for Challo
  pod 'FBSDKLoginKit'
  pod 'Alamofire'

  target 'ChalloTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChalloUITests' do
    # Pods for testing
  end

end
