# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Challo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Challo
  pod “Alamofire”

  target 'ChalloTests' do
    inherit! :search_paths
    # Pods for testing
    pod "Alamofire"
  end

  target 'ChalloUITests' do
    # Pods for testing
    pod "Alamofire"
  end

end
